### ISSUE TITLE
Afinal, qual vai ser a ideia que vamos implementar?

### ISSUE THREAD

**Issue by execb5** [questorama/yummy-chainsaw#1]
Vamos lá pessoal, temos que começar logo o nosso jogo! Sei que ta pegado pra todo mundo, mas precisamos discutir e terminar de decidirmos a ideia.

Eu dei a ideia do bullet hell, não entendi muito bem a ideia da Dani e a do Martin. Vamos usar essa issue para esclarecer as ideias e escolhemos alguma.

**Bullet Hell:**

Aqui ta um exemplo de um bullet hell

![](https://kakeracomplex.files.wordpress.com/2010/09/eosd_screen1.jpg)

É um jogo de tiro cujo objetivo é matar os inimigos e no final de cada fase um chefão. O jogador deve desviar de todos os tiros dos inimigos para sobreviver e atirar para destruir os mesmos.

A característica principal de um *bullet hell*, que diferencia o estilo dos vertical shoot' em up, são os padrões caóticos de tiros. A parte mais difícil de implementar é essa.

Agora falando sobre a minha ideia. Acho que podemos fazer só a luta contra um chefe, assim economizamos na arte dos inimigos e podemos nos concentrar nos multiplos padroes de tiro que esse chefe pode ter. Acho que uns 5 já está de bom tamanho.

**Controles:**
* **Setas** - controlar o personagem
* **Z** - tiro normal
* **X** - especial que limpa os tiros da tela e deixa o jogador invencível por uns segundos
* **RSHIFT** - quando pressionado torna movimentação mais lenta, aumentando precisão

**GUI:**

Toda a interface gráfica ali de cima é completamente dispensável. As únicas coisas que seriam mostradas são:
* Barra de vida do chefão
* Especiais restantes

Tirando o enredo que eu não lembro, a minha idéia é isso. Coloquem a ideia de vocês aqui e vamos decidir!

**Comment by CanTM** [comment]
Eu voto no bullet hell, a minha ideia do gato eu não sei bem como desenvolver, e a Dani também não entendi direito. A do Martin acho que vai ser mais complicada.

**Comment by CanTM** [comment]
Quanto ao enredo
Projeto Coxinha (yummy-chainsaw):
Uma estudante que está vivendo o mundo PUCRS tem seu copo de coxinhas roubado por um monstro gigante

**Comment by djornada** [comment]
Eu voto no bullet hell também, pois é a ideia mais clara que temos

**Comment by execb5** [comment]
@martinduartemore @DanieleSouza 
Por favor, digam o que vcs acham pra gente poder começar a fazer mesmo, tava pensando em fechar a issue amanhã de noite.

**Comment by martinduartemore** [comment]
Oi, eu tava fazendo o trabalho de IA durante o fim de semana, nao cheguei a pensar em nada. Tem como nos reunírmos amanhã de tarde?

**Comment by martinduartemore** [comment]
# Ideia de jogo
---
A ideia seria criar um jogo que explorasse os seguintes elementos:

* **platformer**
* ***fast-paced***
* **geração procedural**

O jogo seria dividido em fases, cujo objetivo primário é chegar na saída o mais rápido possível (o jogador possúi um tempo limite curto para isso). O jogador não possui uma barra de vida, o único jeito de perder é não chegar ao fim da fase dentro do tempo estipulado.

Os obstáculos seriam armadilhas e monstros cujo único objetivo é retardar o jogador (diminuindo sua velocidade, atordoando, imobilizando etc.).

Um dos elementos principais do jogo seria explorar situações de ***risk-reward*** envolvendo o tempo limite. Para isso, cada fase também conteria tesouros, que aumentariam a pontuação final do jogador. Ele deve ou se arriscar e pegar mais tesouros ou seguir para a próxima fase, recebendo menos pontos.

Conforme o jogador avança, as fases vão ficando mais extensas e mais cheias de obstáculos, mas o tempo limite continuaria o mesmo.

## Mecânicas

Uma coisa que teria que ser pensada é como o jogador se deslocaria pela fase (se ele tem *double jump*, *wall jump* etc.).

Eu tinha pensado que o jogador poderia ter também uma espécie de *trinket* que ele poderia ativar pra ganhar invulnerabilidade/imunidade às armadilhas/monstros. Teria um número limitado de cargas (algo como 3), mas ele poderia conseguir mais em baús que poderiam aparecer em fases.

---
## Sobre o projeto
---
O elemento mais importante do jogo é a geração procedural das fases. É o que daria mais trabalho de implementar porque, assim como todo conteúdo gerado proceduralmente em jogos, teríamos que nos preocupar com coisas do tipo:

* É possível completar a fase
* As fases não são monótonas/possuem padrões repetitivos
* Os elementos da fase ficam em lugares apropriados
* O nível de dificuldade pode ser modificado no algoritmo de geração

Tendo a parte da geração procedural, o resto seria bem mais simples de fazer.

Como é um protótipo, não precisamos de tanta variedade de armadilhas/monstros, 1 ou 2 de cada é mais do que o suficiente. A IA dos monstros pode ser bem simples, coisa do tipo andar de um lado pro outro mesmo.

Para a parte artística, podemos usar arte pronta disponível na internet. Seria basicamente:

* *Tileset* para a fase
* Personagem
* Armadilhas
* Monstros
* Tesouros

PS: Talvez fosse interessante se o jogo pudesse ser jogado com controle também. Eu tenho um de Xbox 360 que dá pra usar.

O que vocês acham? Podemos seguir com a ideia do bullet hell também, se quiserem.

**Comment by CanTM** [comment]
Martin, tá bem legal a tua ideia, gostei bastante da parte de geração procedural das fases.

Mas, acho que isso pode levar bastante tempo tempo para ser feito. Também não sou muito fã de jogos nos quais tem que pensar em alguma estratégia com tempo muito limitado, acho que nesse tipo de jogo acaba sendo difícil balancear o grau de dificuldade para que não não fique fácil demais, ou frustrante demais para o jogador.

Ainda estou mais interessada no bullet hell, principalmente na parte da geração dos padrões de tiros e em como administrar tantos objetos na mesma cena.

Voto no bullet hell

**Comment by DanieleSouza** [comment]
Eu achei a ideia do Martin interessante e acho que ela me motiva mais que o bullet hell. Meu voto vai para ela. Apesar de termos pouco tempo, acho que podemos nos organizar para fazer uma versão simples desse jogo. Somos 5. Com planejamento e foco no que é essencial, acho que podemos conseguir. Mas se a maioria preferir o bullet hell, por mim tudo bem.

**Comment by djornada** [comment]
Eu prefiro o bullet hell, a parte artística é traqnuila, e a difculdae toda ta na técnica de conseguir ter 75%(ou mais) da tela com ibjetos se movendo e ainda manter a performance.

**Comment by martinduartemore** [comment]
Ficou decidido o bullet hell, então?

**Comment by execb5** [comment]
Sim.

E mais uma vez enfatizo o uso das issues porque fica bem documentado todas as decisões tomadas, e sem contar que caso o @martinduartemore queira lembrar da ideia dele, ou nós mesmos desenvolvermos ela no semestre seguinte, é só olhar aqui.
