### ISSUE TITLE
Implementar a pool de bullets

### ISSUE THREAD

**Issue by execb5** [questorama/yummy-chainsaw#10]
Uma pool de bullets para ser usada por todos os emitters de bullets. Para não ter processo de instanciação e destruição de objetos a cada frame.

**Comment by CanTM** [comment]
http://gameprogrammingpatterns.com/object-pool.html

**Comment by CanTM** [comment]
http://unity3d.com/pt/learn/tutorials/modules/beginner/live-training-archive/object-pooling

**Comment by CanTM** [comment]
Pessoal, implementei a classe ObjectPool, e junto estou fazendo as Bullets, para serem usadas pela pool.

Como atributos para Bullet, pensei em velocidade e ângulo, mas, se vamos ter os tiros se movendo em padrões diferentes do que simplesmente em linha reta, acho que seria bom colocar também um array, para determinar a trajetória do tiro.

Acham que isso pode funcionar?

**Comment by execb5** [comment]
Não entendi mtu bem como q tu usaria o array, mas tenta. Acho que ninguém aqui tem mtu ideia de como fazer.

**Comment by CanTM** [comment]
Mandei um pull request.
Somente cria a classe, não tem nenhum outro script chamando ela. 
Quando ela for ser usada, o script que "pegar" um objeto da pool deve incluir a seguinte linha de código:
       gameObject.SetActive (true);

E o que for "destruir" o objeto:
       gameObject.SetActive (false);

Sendo "gameObject" o objeto da pool
