### ISSUE TITLE
Colocar a classe Boundary em um arquivo separado

### ISSUE THREAD

**Issue by execb5** [questorama/yummy-chainsaw#17]
Ela está dentro da ShipBehavior

**Comment by martinduartemore** [comment]
Está feito no meu fork:

![boundaryclass](https://cloud.githubusercontent.com/assets/7947653/10587247/085cbb26-767f-11e5-9bad-4e7f82083835.png)

Está como *Serializable* pra gente poder continuar editando no Inspector da Unity como estávamos fazendo. Logo vou mandar um pull request, só estou fazendo outras coisas em conjunto.

Está bom assim?

**Comment by execb5** [comment]
Blz, perfeito.

**Comment by CanTM** [comment]
Ótimo, mas sugiro que mande pull request por issue, mesmo que sejam poucas alterações
