### ISSUE TITLE
Sobre a versão da unity...

### ISSUE THREAD

**Issue by execb5** [questorama/yummy-chainsaw#2]
Se vamos sempre trabalhar de casa, sugiro usarmos a última versão da unity. Se a gente for desenvolver no laboratório de cg, temos que ver qual é a versão que tem lá pra gente baixar a mesma nos pcs de casa.

Eu acho que fica melhor usar a mesma do lab de CG. Acho que não tem problema no fato de ser a Pro, e a que a gente fosse baixar ser a Free. Só não vamos poder utilizar as coisas que só tem na Pro.

O que vocês preferem?

**Comment by CanTM** [comment]
Eu prefiro usar a mesma versão que tem no lab de CG, quando tivermos tempo podemos nos encontrar na puc para desenvolvermos juntos

**Comment by djornada** [comment]
Concordo com a @CanTM em usar a mesma versão que tem no lab de CG. Se um dia a gente resolver usar uma versão nova a unity mesmo migra o projeto.

**Comment by execb5** [comment]
Aí é que ta @djornada, migrar projetos da 4.x pra 5.x não funciona. Eu tinha testado com meus projetinho aqui no desk quando baixei a unity 5 e ficou tudo errado e não funcionando direito. Por isso precisamos ser consistentes na versão que vamos usar.

**Comment by CanTM** [comment]
É, não funcionou pra mim também, mas ainda assim prefiro fazer na que tiver na 401.

**Comment by execb5** [comment]
Vamos ver qual é a versão que tem no lab de cg, então. É bom tbm pq a maioria dos tutoriais que tem pelo youtube são de unity 4.x, pelo que eu lembre.

**Comment by djornada** [comment]
@execb5 e @CanTM Tudo bem vamos escolher e ir até o fim com a versão que a escolhermos, eu pensei que fosse de boa pq eu migrei da 4 pra 5 e não tiver problemas ;)

**Comment by CanTM** [comment]
Versão da Unity na sala 401 é 4.6.3f1
