### ISSUE TITLE
Geração procedural de sprites para inimigos

### ISSUE THREAD

**Issue by martinduartemore** [questorama/yummy-chainsaw#24]
Pra nos ajudar com geração de conteúdo e "enriquecer" um pouco mais o nosso jogo, seria interessante gerarmos sprites para inimigos proceduralmente, como havíamos comentado.

Eu havia pensado em sprites estilo **Space Invaders**. São relativamente simples e, ao mesmo tempo, interessantes.

Alguns exemplos:

![invaders1](https://cloud.githubusercontent.com/assets/7947653/10587446/ceec3582-767f-11e5-97eb-c757bd4d89f0.jpg)

![invaders2](https://cloud.githubusercontent.com/assets/7947653/10587451/d2d5eae4-767f-11e5-97a0-62d337279d27.jpg)

**Comment by martinduartemore** [comment]
Eu fiz uma verão de teste no meu fork, hoje de noite posto aqui os resultados.

**Comment by execb5** [comment]
Acho q vai ficar massa com as sprites nesse estilo.

**Comment by CanTM** [comment]
Parece bem legal pra mim

**Comment by martinduartemore** [comment]
Aqui vão alguns exemplos do gerador que eu fiz ontem:

5x5:
![5x5](https://cloud.githubusercontent.com/assets/7947653/10617635/4820c98e-774a-11e5-8142-14f279489fc2.gif)

8x8:
![8x8](https://cloud.githubusercontent.com/assets/7947653/10617670/69783734-774a-11e5-9330-6e61edd7a988.gif)

10x10:
![10x10](https://cloud.githubusercontent.com/assets/7947653/10617673/6c95fafa-774a-11e5-878c-9df5fb781e2d.gif)

O gerador escolhe aleatóreamente pixels pra "ligar" e depois espelha no eixo X.
Ele também escolhe aleatóreamente a cor do sprite (eu botei nesse exemplo só cores mais claras, já que o jogo vai ter um fundo escuro é melhor ter sprites mais claros eu acho).

Tá beeem simples, mas acho que dá pra usar assim já...

Que tamanho de sprite vocês acham que ficou melhor?

**Comment by martinduartemore** [comment]
Eu queria deixar com o efeito de glow da imagem de cima, mas ainda não encontrei um jeito de fazer usando a Unity 4.X sem pagar. Na Unity 5 tem esse efeito de graça.

**Comment by execb5** [comment]
Curti o jeito q ficam as sprites, é bem legal.
O  tamanho só testando pra gente decidir, pq do jeito q ta ta tudo muito grande, pelos menos pra mim.
O efeito de glow fica bem legal, mas igual não tem problema ficar sem.

**Comment by martinduartemore** [comment]
Eles ficaram todos grandes porque eu afastei/aproximei a câmera de um jeito diferente pra cada um dos casos pra caber todos na tela. Vou dar mais uma olhada depois na questão do glow...
