### ISSUE TITLE
Criar GDD

### ISSUE THREAD

**Issue by CanTM** [questorama/yummy-chainsaw#4]
Que tal criarmos uma versão do GDD em markdown no Git mesmo até termos ele completo?

**Comment by execb5** [comment]
Eu pilho markdown sempre, acho lindo. hahaha

Mas a gente precisa de GDD mesmo?

**Comment by CanTM** [comment]
Eu acho que sim, para termos onde consultar enquanto estivermos implementando o jogo
Como ele vai sofrer alterações ao longo do desenvolvimento, pensamos em deixar ele em markdown ao invés de .doc

**Comment by djornada** [comment]
@execb5 Acho bom a genter ter como um guia, 
quanto ao markdown <3. É fácil de versionar e ver o que cada um alterou.
