### ISSUE TITLE
Definir Processo de Desenvolvimento

### ISSUE THREAD

**Issue by djornada** [questorama/yummy-chainsaw#5]
Gente como vamos usar o git eu acho legal a gente ter um processo de como trabalhar usando o git e documentar para que possamos ter um padrão de trabalho.
Eu tenho uma idéia de como podemos fazer, só quero saber o que vocês acham.

**Comment by CanTM** [comment]
Eu acho uma boa, assim podemos revisar os códigos uns dos outros também antes de dar merge no repositório

**Comment by execb5** [comment]
Por mim pode ser tanto usando diferentes *branches* ou usando o esquema de *fork* e *pull request*.

Estou aberto a sugestões.

**Comment by CanTM** [comment]
execb5, qual é a diferença entre esses dois processos?

**Comment by CanTM** [comment]
djornada, qual é a tua ideia?

**Comment by djornada** [comment]
Minha ideia é utilizar pull request mesmo, assim podemos avaliar o código e dar palpites de melhoria.
No findi vou tentar fazer algo pra exemplificar isso

**Comment by CanTM** [comment]
Por mim pode ser por pull request

@DanieleSouza @martinduartemore alguma sugestão?

**Comment by execb5** [comment]
Ficou definido por **pull request**
